apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: unir-practica2
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
